install:
  - cinst nodejs.install -x86
  - set PATH=%PATH%;"C:\Program Files (x86)\nodejs\"

build_script:
  - git submodule update --init
  - npm install
  - node-gyp rebuild --msvs-version=2012

platforms:
  - x32