install:
  - cinst nodejs.install -x86
  - dir "C:\Program Files (x86)\nodejs\"
  - cd "C:\Program Files (x86)\nodejs\" & npm install -g npm
  - npm "-v"
  - cd "c:\" & npm "-v"

build_script:
  - git submodule update --init
  - npm install
  - node-gyp rebuild --msvs-version=2012

platforms:
  - x32