install:
  - cinst nodejs.install
  - cinst nodejs.install -x86
  - npm install -g node-shyp 

build_script:
  - git submodule update --init
  - npm install
  - node-gyp rebuild --msvs-version=2012

platforms:
  - x32